/*
 * This file is generated by jOOQ.
 */
package com.uno.getinline;


import com.uno.getinline.tables.Admin;
import com.uno.getinline.tables.AdminPlaceMap;
import com.uno.getinline.tables.Event;
import com.uno.getinline.tables.Place;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Getinline extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>getinline</code>
     */
    public static final Getinline GETINLINE = new Getinline();

    /**
     * The table <code>getinline.admin</code>.
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>getinline.admin_place_map</code>.
     */
    public final AdminPlaceMap ADMIN_PLACE_MAP = AdminPlaceMap.ADMIN_PLACE_MAP;

    /**
     * The table <code>getinline.event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>getinline.place</code>.
     */
    public final Place PLACE = Place.PLACE;

    /**
     * No further instances allowed
     */
    private Getinline() {
        super("getinline", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Admin.ADMIN,
            AdminPlaceMap.ADMIN_PLACE_MAP,
            Event.EVENT,
            Place.PLACE);
    }
}
