/*
 * This file is generated by jOOQ.
 */
package com.uno.getinline;


import com.uno.getinline.tables.Admin;
import com.uno.getinline.tables.AdminPlaceMap;
import com.uno.getinline.tables.Event;
import com.uno.getinline.tables.Place;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in getinline.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENT_IDX_1BC18D95691E942C6BE0582FC = Internal.createIndex(DSL.name("idx_1bc18d95691e942c6be0582fc"), Event.EVENT, new OrderField[] { Event.EVENT.MODIFIED_AT }, false);
    public static final Index ADMIN_IDX_356C59A80FBD29AAAA24D7882 = Internal.createIndex(DSL.name("idx_356c59a80fbd29aaaa24d7882"), Admin.ADMIN, new OrderField[] { Admin.ADMIN.MODIFIED_AT }, false);
    public static final Index PLACE_IDX_3EB99BE2C6DF3DCD9FB790099 = Internal.createIndex(DSL.name("idx_3eb99be2c6df3dcd9fb790099"), Place.PLACE, new OrderField[] { Place.PLACE.PHONE_NUMBER }, false);
    public static final Index PLACE_IDX_4D2DAD1171AB1101220C1BDE4 = Internal.createIndex(DSL.name("idx_4d2dad1171ab1101220c1bde4"), Place.PLACE, new OrderField[] { Place.PLACE.CREATED_AT }, false);
    public static final Index PLACE_IDX_51ECEAA568455E24788D07974 = Internal.createIndex(DSL.name("idx_51eceaa568455e24788d07974"), Place.PLACE, new OrderField[] { Place.PLACE.MODIFIED_AT }, false);
    public static final Index EVENT_IDX_70BB5090E97A9C774FC8145F1 = Internal.createIndex(DSL.name("idx_70bb5090e97a9c774fc8145f1"), Event.EVENT, new OrderField[] { Event.EVENT.CREATED_AT }, false);
    public static final Index PLACE_IDX_8937D5DFB2707F816927AA988 = Internal.createIndex(DSL.name("idx_8937d5dfb2707f816927aa988"), Place.PLACE, new OrderField[] { Place.PLACE.PLACE_NAME }, false);
    public static final Index ADMIN_IDX_927C399BA7EE32F041A096FE5 = Internal.createIndex(DSL.name("idx_927c399ba7ee32f041a096fe5"), Admin.ADMIN, new OrderField[] { Admin.ADMIN.CREATED_AT }, false);
    public static final Index EVENT_IDX_92D25CEF60C9A3ED64BC291C7 = Internal.createIndex(DSL.name("idx_92d25cef60c9a3ed64bc291c7"), Event.EVENT, new OrderField[] { Event.EVENT.EVENT_START_DATETIME }, false);
    public static final Index EVENT_IDX_9F2FE388036352060533E460A = Internal.createIndex(DSL.name("idx_9f2fe388036352060533e460a"), Event.EVENT, new OrderField[] { Event.EVENT.EVENT_END_DATETIME }, false);
    public static final Index ADMIN_PLACE_MAP_IDX_B7AC127882C206DC0D1C3BC21 = Internal.createIndex(DSL.name("idx_b7ac127882c206dc0d1c3bc21"), AdminPlaceMap.ADMIN_PLACE_MAP, new OrderField[] { AdminPlaceMap.ADMIN_PLACE_MAP.MODIFIED_AT }, false);
    public static final Index EVENT_IDX_C94B41F3F084C10B88FAA3F52 = Internal.createIndex(DSL.name("idx_c94b41f3f084c10b88faa3f52"), Event.EVENT, new OrderField[] { Event.EVENT.EVENT_NAME }, false);
    public static final Index PLACE_IDX_D5922C3BF14EB0FCB470AADE5 = Internal.createIndex(DSL.name("idx_d5922c3bf14eb0fcb470aade5"), Place.PLACE, new OrderField[] { Place.PLACE.ADDRESS }, false);
    public static final Index ADMIN_PLACE_MAP_IDX_E095EDD8EC09EC05343F1BD06 = Internal.createIndex(DSL.name("idx_e095edd8ec09ec05343f1bd06"), AdminPlaceMap.ADMIN_PLACE_MAP, new OrderField[] { AdminPlaceMap.ADMIN_PLACE_MAP.CREATED_AT }, false);
    public static final Index ADMIN_IDX_FDF4B3F793FF020A028A46CB1 = Internal.createIndex(DSL.name("idx_fdf4b3f793ff020a028a46cb1"), Admin.ADMIN, new OrderField[] { Admin.ADMIN.PHONE_NUMBER }, false);
}
