/*
 * This file is generated by jOOQ.
 */
package com.uno.getinline.tables.pojos;


import com.uno.getinline.constant.EventStatus;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Event implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long          id;
    private final Long          placeId;
    private final String        eventName;
    private final EventStatus   eventStatus;
    private final LocalDateTime eventStartDatetime;
    private final LocalDateTime eventEndDatetime;
    private final Integer       currentNumberOfPeople;
    private final Integer       capacity;
    private final String        memo;
    private final LocalDateTime createdAt;
    private final LocalDateTime modifiedAt;

    public Event(Event value) {
        this.id = value.id;
        this.placeId = value.placeId;
        this.eventName = value.eventName;
        this.eventStatus = value.eventStatus;
        this.eventStartDatetime = value.eventStartDatetime;
        this.eventEndDatetime = value.eventEndDatetime;
        this.currentNumberOfPeople = value.currentNumberOfPeople;
        this.capacity = value.capacity;
        this.memo = value.memo;
        this.createdAt = value.createdAt;
        this.modifiedAt = value.modifiedAt;
    }

    public Event(
        Long          id,
        Long          placeId,
        String        eventName,
        EventStatus   eventStatus,
        LocalDateTime eventStartDatetime,
        LocalDateTime eventEndDatetime,
        Integer       currentNumberOfPeople,
        Integer       capacity,
        String        memo,
        LocalDateTime createdAt,
        LocalDateTime modifiedAt
    ) {
        this.id = id;
        this.placeId = placeId;
        this.eventName = eventName;
        this.eventStatus = eventStatus;
        this.eventStartDatetime = eventStartDatetime;
        this.eventEndDatetime = eventEndDatetime;
        this.currentNumberOfPeople = currentNumberOfPeople;
        this.capacity = capacity;
        this.memo = memo;
        this.createdAt = createdAt;
        this.modifiedAt = modifiedAt;
    }

    /**
     * Getter for <code>getinline.event.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>getinline.event.place_id</code>.
     */
    public Long getPlaceId() {
        return this.placeId;
    }

    /**
     * Getter for <code>getinline.event.event_name</code>.
     */
    public String getEventName() {
        return this.eventName;
    }

    /**
     * Getter for <code>getinline.event.event_status</code>.
     */
    public EventStatus getEventStatus() {
        return this.eventStatus;
    }

    /**
     * Getter for <code>getinline.event.event_start_datetime</code>.
     */
    public LocalDateTime getEventStartDatetime() {
        return this.eventStartDatetime;
    }

    /**
     * Getter for <code>getinline.event.event_end_datetime</code>.
     */
    public LocalDateTime getEventEndDatetime() {
        return this.eventEndDatetime;
    }

    /**
     * Getter for <code>getinline.event.current_number_of_people</code>.
     */
    public Integer getCurrentNumberOfPeople() {
        return this.currentNumberOfPeople;
    }

    /**
     * Getter for <code>getinline.event.capacity</code>.
     */
    public Integer getCapacity() {
        return this.capacity;
    }

    /**
     * Getter for <code>getinline.event.memo</code>.
     */
    public String getMemo() {
        return this.memo;
    }

    /**
     * Getter for <code>getinline.event.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>getinline.event.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return this.modifiedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Event (");

        sb.append(id);
        sb.append(", ").append(placeId);
        sb.append(", ").append(eventName);
        sb.append(", ").append(eventStatus);
        sb.append(", ").append(eventStartDatetime);
        sb.append(", ").append(eventEndDatetime);
        sb.append(", ").append(currentNumberOfPeople);
        sb.append(", ").append(capacity);
        sb.append(", ").append(memo);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(modifiedAt);

        sb.append(")");
        return sb.toString();
    }
}
