spring:

  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL #;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    #    url: jdbc:h2:tcp://localhost/~/test;MODE=MYSQL
    #    driver-class-name: org.h2.Driver
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      #      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
    #        globally_quoted_identifiers: true
    #        storage_engine: innodb
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: h2
  #    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

