server:
  port: 18080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    #    database-platform: mysql
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/msa_gift?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
  flyway:
    user: root
    password: root
    schemas: gift
    url: jdbc:mysql://localhost:3306/msa_gift?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

logging:
  config: classpath:logback-local.xml

example.order:
  base-url: http://localhost:8080/

cloud:
  aws:
    access-key: aaaa
    secret-key: bbbb