version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: inf-death-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpassword1234
    ports:
      - "27018:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongo_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://root:example@localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  mongo_config: