spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

#logging:
#  level:
#    org.springframework.batch: DEBUG
#    org.springframework.jdbc.datasource: DEBUG
