spring:
  main:
    banner-mode: OFF
  application:
    name: dgs-web
  datasource:
    url: jdbc:h2:mem:testdb                 # H2 ??????? ??? ??? ?? (?????? ??? 'testdb')
    driver-class-name: org.h2.Driver        # H2 ?????? ???? ??? ??
    username: sa                            # ?? ???? (H2? ???)
    password:                               # ?? ????? ? ? (H2? ???)
  h2:
    console:
      enabled: true                         # H2 ?? ??? (? ?????? ??????? ??? ? ??)
      path: /h2-console                     # H2 ??? ??? ? ?? ?? ?? (?: http://localhost:8080/h2-console)
  jpa:
    hibernate:
      ddl-auto: update                      # ?????? ?? ? ??? ???? ?????? ???? ????
    show-sql: true                          # ???? SQL ??? ??? ???? ???? ??
  sql:
    init:
      mode: always                          # ?????? ??? ?? ?? (?? ??)

#  graphql:
#    schema:
#      locations: classpath:graphql          # GraphQL ??? ?? ?? ??

dgs:
  graphql:
    path: /graphql                          # GraphQL ????? ?? ??
    schema-locations: classpath*:schema/**/*.graphql*        # GraphQL ??? ?? ?? ??
    schema-printer:
      enabled: true                         # ?????? ?? ? GraphQL ???? ??
    websocket:
      connection-init-timeout: 60s          # WebSocket ?? ??? ???? ??
    spring:
      webmvc:
        async-dispatch:
          enabled: true                     # GraphQL ??? ?? ??? ???? ???

  graphiql:
    enabled: true                           # GraphiQL ????? ???
    path: /graphiql                         # GraphiQL ?? ??
    ws-path: /subscriptions                 # GraphQL Subscription? ?? WebSocket ??

  playground:
    enabled: true                           # GraphQL Playground ???
    path: /playground                       # Playground ?? ??
