
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/test  # ?? url
    driver-class-name: org.h2.Driver        # JDBC Driver
    username: sa                            # userID
    password:                               # password

  jpa:
    database: h2
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect #Dialect, ?? ??
#        show_sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: create-drop
