version: '3.8'
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_DATASOURCES_VARIABLES_DS_K6=InfluxDB
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./scripts:/scripts
    depends_on:
      - influxdb
    # command: ["run", "--out", "influxdb=http://influxdb:8086/k6", "/scripts/testscript.js"]

volumes:
  influxdb-data:
  grafana-data:
