spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
    root: info

#server:
#  port: 18082

server:
  port: 8082

