debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    com.uno.getinline: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.jooq: debug

spring:
  thymeleaf:
    cache: false
    decoupled-logic: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      format_sql: true
      properties:
        hibernate:
          default_batch_fetch_size: 100
    show-sql: true
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/getinline
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  custom-jooq:
    format-sql: true
  data:
    rest:
      base-path: /api
