
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:5431/todo?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 303ehd

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate : info

---

