server:
  port: 18081

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecommerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true

    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

#graphql:
#  tools:
#    schema-location-pattern: "**/*.graphqls"