services:
  mysql:
    image: mysql:8.0.40
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: messagesystem
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
