management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      client:
        period: 1000ms # 주기적으로 서버랑 통신하는 주기.
        url:
          - http://127.0.0.1:9090  # spring boot admin 서버의 ip, port 기입\


server:
  port: 8081