
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/h2/test  # ?? url
    url : jdbc:h2:mem:jpashop
    driver-class-name: org.h2.Driver        # JDBC Driver
    username: sa                            # userID
    password:                               # password

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    database: h2
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect #Dialect, ?? ??
        show_sql: true
        format_sql: true
        use_sql_comments: true
        id:
          new_generator_mappings: true
    hibernate:
      ddl-auto: update

