spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_manage  # MySQL ?????? URL, ???? 'student_manage' ??????? ??
    username: root                                    # ?????? ???? ??? ????
    password: root                                    # ?????? ???? ??? ????
    driver-class-name: com.mysql.cj.jdbc.Driver       # MySQL ?????? ???? ???

  jpa:
    database: mysql                                   # JPA?? ??? ?????? ?? (MySQL)
    hibernate:
      ddl-auto: update                                # ?????? ?? ? ???? ???? ?? ?? ?????? ??
    show-sql: false                                   # SQL ??? ??? ???? ?? (false? ???? ???? ??)

  graphql:
    websocket:
      path: /subscription                             # GraphQL ??? ?? ?? ?? (??????? ?? ?????)
#    path: /apis   # /apis? ???? localhost:8080/apis                                    # GraphQL API ????? ?? ??

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect        # Hibernate?? ??? MySQL ?? (MySQL 8? ?? SQL ?? ??)
