spring:
  application:
    name: ex1
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

  app:
    jwtExpirationMs: 3000000

logging:
  level:
    root: INFO

app:
  jwt:
    secret: "Oh! My GraphQL Secret Key, You should be at least - 168 bites long inorder for to secure JWT HMAC-SHA algorithm. You make sure you are long enough not be vulnerable."
  systemUser:
    login:
      user: graphql@example.com
      password: password
