
spring:
  application:
    name: core-api
  profiles:
    active: local

  config:
#    import:
#      - monitoring.yml
      - logging.yml
      - db-core.yml
#      - client-example.yml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: local-dev

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: staging

---

spring:
  config:
    activate:
      on-profile: live
